import React, { useMemo, useState } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { MapContainer, TileLayer, CircleMarker, Popup, useMap } from 'react-leaflet';
import { BarChart, Bar, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, LineChart, Line } from 'recharts';
import { ArrowUpRight, BarChart3, Bot, ChevronRight, CircleHelp, Database, Filter, Layers3, MapPinned, MessageSquareText, Search, ShieldCheck, TrendingUp, WalletCards, X } from 'lucide-react';
import { civicData, useCivicData } from '../services/civicData';
import { PriorityProject } from '../types/civic';

const money = (n: number) => `₹${(n / 10000000).toFixed(2)} Cr`;
const langName = (x: string) => x === 'bn' ? 'Bengali' : x === 'hi' ? 'Hindi' : 'English';

function MapFocus({ wardId }: { wardId: string }) { const map = useMap(); const ward = civicData.getWard(wardId); React.useEffect(() => { if (ward) map.setView(ward.centroid, 12.7, { animate: true }) }, [ward, map]); return null }

const KPI: React.FC<{ label: string, value: string, sub: string, icon: React.ReactNode }> = ({ label, value, sub, icon }) => <div className="kpi-card"><div className="kpi-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>;

export const GovernmentPage: React.FC = () => {
    const data = useCivicData();
    const { pathname } = useLocation(); const [country, setCountry] = useState('India'); const [city, setCity] = useState('Kolkata'); const [selected, setSelected] = useState('WARD-12'); const [search, setSearch] = useState(''); const [category, setCategory] = useState('All'); const [assistant, setAssistant] = useState(''); const [chat, setChat] = useState<{ q: string, a: string }[]>([]);
    const section = pathname.split('/')[2] || 'overview';
    const filteredRequests = useMemo(() => civicData.requests.filter(r => (category === 'All' || r.category === category) && (!search || r.text.toLowerCase().includes(search.toLowerCase()) || r.ward.toLowerCase().includes(search.toLowerCase()))), [category, search]);
    if (data.loading) return <div className="gov-app"><div className="gov-main"><div className="gov-content" style={{ display: 'grid', placeItems: 'center', minHeight: '70vh' }}><div className="gov-card" style={{ padding: 28, textAlign: 'center' }}><strong>Loading CivicSignal dataset…</strong><p className="muted" style={{ marginTop: 8 }}>{data.error || 'Connecting to MongoDB-backed dataset.'}</p></div></div></div></div>;
    if (data.error || !data.loaded) return <div className="gov-app"><div className="gov-main"><div className="gov-content" style={{ display: 'grid', placeItems: 'center', minHeight: '70vh' }}><div className="gov-card" style={{ padding: 28, textAlign: 'center' }}><strong>Dataset unavailable</strong><p className="muted" style={{ marginTop: 8 }}>{data.error || 'Run the dataset seed command on the backend.'}</p><button className="btn btn-primary" style={{ marginTop: 16 }} onClick={() => data.reload()}>Retry</button></div></div></div></div>;
    const selectedWard = civicData.getWard(selected)!; const selectedReq = civicData.getRequests(selected); const project = civicData.projects.find(x => x.wardId === selected)!;
    const ask = () => { if (!assistant.trim()) return; const q = assistant.trim(); const l = q.toLowerCase(); let a = 'The MongoDB dataset combines citizen requests with analytical ward infrastructure and investment indicators.'; if (l.includes('highest') || l.includes('drainage')) { const p = [...civicData.projects].sort((x, y) => y.demand - x.demand).slice(0, 3).map(x => x.wardName).join(', '); a = `The strongest drainage-related demand signals in the dataset are concentrated in ${p}. Review the evidence panels for the contributing factors.` } else if (l.includes('ward 12') || l.includes('ballygunge')) a = `Ballygunge has ${selectedReq.length} dataset requests. Its analytical priority score is ${project.score}/100, supported by demand, severity, infrastructure gap and investment gap factors.`; else if (l.includes('investment')) a = `Across the dataset, investment values are analytical/simulated. The dashboard compares allocated budgets and completion with citizen demand; it does not represent official government spending.`; setChat(c => [...c, { q, a }]); setAssistant(''); };
    const navItems = [['overview', 'Overview'], ['hotspots', 'Demand Hotspots'], ['gaps', 'Infrastructure Gaps'], ['investments', 'Investment Gaps'], ['projects', 'Priority Projects'], ['requests', 'Citizen Requests'], ['assistant', 'AI Assistant']];
    return <div className="gov-app">
        <aside className="gov-sidebar"><Link to="/" className="gov-brand"><span className="brand-mark">CS</span><span><strong>CivicSignal</strong><small>Government Command Center</small></span></Link><div className="sidebar-demo"><span>MONGODB</span> Live dataset</div><nav>{navItems.map(([id, label]) => <NavLink key={id} to={id === 'overview' ? '/government' : `/government/${id}`} className={({ isActive }) => isActive ? 'active' : ''}><span className="nav-icon">{id === 'overview' ? <BarChart3 /> : id === 'hotspots' ? <MapPinned /> : id === 'gaps' ? <Layers3 /> : id === 'investments' ? <WalletCards /> : id === 'projects' ? <TrendingUp /> : id === 'requests' ? <MessageSquareText /> : <Bot />}</span>{label}</NavLink>)}</nav><div className="sidebar-bottom"><div className="secure-note"><ShieldCheck size={16} /><span><b>Decision support</b><small>AI does not make official decisions.</small></span></div><Link to="/submit" className="citizen-link">Open citizen portal →</Link></div></aside>
        <main className="gov-main"><header className="gov-topbar"><div><span className="eyebrow">PUBLIC INFRASTRUCTURE INTELLIGENCE</span><h1>{section === 'overview' ? 'National-to-local demand overview' : navItems.find(x => x[0] === section)?.[1]}</h1></div><div className="top-controls"><label>Country<select value={country} onChange={e => setCountry(e.target.value)}><option>India</option><option>Brazil</option><option>Russia</option><option>China</option><option>South Africa</option></select></label><label>City<select value={city} onChange={e => setCity(e.target.value)}><option>Kolkata</option><option>São Paulo</option><option>Johannesburg</option><option>Shanghai</option></select></label><span className="live-badge"><span /> MongoDB connected</span></div></header>
            <div className="gov-content"><div className="gov-context-banner"><Database size={16} /><span><b>MONGODB DATASET</b> — interface data is loaded from the seeded CivicSignal dataset. Values are analytical/synthetic and must not be presented as official statistics.</span><button aria-label="Dismiss"><X size={15} /></button></div>
                {(section === 'overview' || section === 'hotspots') && <OverviewSection selected={selected} setSelected={setSelected} selectedWard={selectedWard} project={project} />}
                {section === 'gaps' && <GapsSection />}
                {section === 'investments' && <InvestmentSection />}
                {section === 'projects' && <ProjectsSection project={project} setSelected={setSelected} />}
                {section === 'requests' && <RequestsSection requests={filteredRequests} search={search} setSearch={setSearch} category={category} setCategory={setCategory} />}
                {section === 'assistant' && <AssistantSection assistant={assistant} setAssistant={setAssistant} ask={ask} chat={chat} />}
            </div></main>
    </div>
};

const OverviewSection: React.FC<{ selected: string, setSelected: (x: string) => void, selectedWard: typeof civicData.wards[number], project: PriorityProject }> = ({ selected, setSelected, selectedWard, project }) => {
    const wardReq = civicData.getRequests(selected); const catCounts = Object.entries(wardReq.reduce<Record<string, number>>((a, r) => (a[r.category] = (a[r.category] || 0) + 1, a), {})).map(([name, value]) => ({ name, value }));
    return <div className="dashboard-stack">
        <div className="kpi-grid"><KPI label="Citizen requests" value={civicData.requests.length.toLocaleString()} sub="loaded from MongoDB dataset" icon={<MessageSquareText />} /><KPI label="Active demand clusters" value={civicData.clusters.length.toLocaleString()} sub="dataset clusters" icon={<Layers3 />} /><KPI label="Infrastructure hotspots" value={civicData.wards.length.toLocaleString()} sub="dataset wards" icon={<MapPinned />} /><KPI label="Priority regions" value={civicData.projects.filter(p => p.score >= 70).length.toLocaleString()} sub="analytical score ≥ 70" icon={<TrendingUp />} /></div>
        <div className="story-strip"><span>VOICE OF CITIZENS</span><ChevronRight /><span>UNDERSTAND</span><ChevronRight /><span>AGGREGATE</span><ChevronRight /><span>LOCATE</span><ChevronRight /><span>ANALYSE</span><ChevronRight /><span>COMPARE</span><ChevronRight /><span>PRIORITIZE</span><ChevronRight /><span>RECOMMEND</span></div>
        <div className="dashboard-grid map-grid">
            <section className="gov-card map-card"><div className="card-header"><div><span className="section-label">GEOGRAPHIC DEMAND</span><h2>Citizen demand hotspots</h2></div><span className="metric-pill"><MapPinned size={14} /> {civicData.wards.length} wards</span></div><div className="map-wrap"><MapContainer center={[22.57, 88.36]} zoom={11} scrollWheelZoom className="gov-map"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><MapFocus wardId={selected} />{civicData.wards.map(w => { const count = civicData.getRequests(w.id).length; const p = civicData.projects.find(x => x.wardId === w.id)!; return <CircleMarker key={w.id} center={w.centroid} radius={Math.max(7, Math.min(20, 6 + count / 2))} pathOptions={{ color: w.id === selected ? '#0b6b68' : '#1f4e79', weight: w.id === selected ? 4 : 2, fillOpacity: .62, fillColor: p.score >= 75 ? '#0f766e' : p.score >= 60 ? '#2d6193' : '#89aeCD' }} eventHandlers={{ click: () => setSelected(w.id) }}><Popup><b>{w.name}</b><br />{count} citizen requests<br />Priority score: {p.score}/100</Popup></CircleMarker> })}</MapContainer></div><div className="map-foot"><span><i className="legend-dot high" />Higher analytical priority</span><span><i className="legend-dot mid" />Moderate signal</span><span>Click a ward to inspect evidence</span></div></section>
            <section className="gov-card region-card"><div className="card-header"><div><span className="section-label">REGION DETAIL</span><h2>{selectedWard.name}</h2></div><span className="score-badge">{project.score}<small>/100</small></span></div><p className="muted">{selectedWard.zone} · population {selectedWard.population.toLocaleString()}</p><div className="detail-metrics"><div><span>Citizen demand</span><strong>{project.demand}/100</strong></div><div><span>Infrastructure gap</span><strong>{project.infrastructureGap}/100</strong></div><div><span>Investment gap</span><strong>{project.investmentGap}/100</strong></div><div><span>Affected population</span><strong>{project.affectedPopulation.toLocaleString()}</strong></div></div><div className="why-panel"><div className="why-title"><CircleHelp size={16} /> WHY THIS PRIORITY?</div><ul>{project.evidence.map(x => <li key={x}>{x}</li>)}</ul></div><div className="recommendation"><span>RECOMMENDED INTERVENTION</span><strong>{project.title}</strong><small>Confidence {Math.round(project.confidence * 100)}% · analytical prototype recommendation</small></div></section>
        </div>
        <div className="dashboard-grid charts-grid"><section className="gov-card"><div className="card-header"><div><span className="section-label">DEMAND TREND</span><h2>Citizen demand vs investment</h2></div></div><div className="chart"><ResponsiveContainer width="100%" height={240}><LineChart data={civicData.trends}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" /><YAxis /><Tooltip /><Line type="monotone" dataKey="demand" stroke="#1f4e79" strokeWidth={3} dot={false} /><Line type="monotone" dataKey="investment" stroke="#2d7d6e" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></div></section><section className="gov-card"><div className="card-header"><div><span className="section-label">WARD PROFILE</span><h2>{selectedWard.name} issue mix</h2></div></div><div className="chart"><ResponsiveContainer width="100%" height={240}><BarChart data={catCounts}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" tick={{ fontSize: 10 }} interval={0} /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="value" fill="#2d6193" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></section></div>
    </div>
};

const GapsSection: React.FC = () => <div className="dashboard-stack"><div className="section-intro"><div><span className="section-label">INFRASTRUCTURE GAP ANALYSIS</span><h2>Where service conditions trail community demand</h2><p>Gap indicators are derived from simulated infrastructure profiles. They are evidence signals, not official service ratings.</p></div></div><div className="gap-grid">{civicData.wards.slice(0, 10).map(w => { const i = civicData.infrastructure.find(x => x.wardId === w.id)!; const p = civicData.projects.find(x => x.wardId === w.id)!; return <div className="gov-card gap-card" key={w.id}><div className="gap-head"><div><strong>{w.name}</strong><small>{w.id}</small></div><span>{p.infrastructureGap}/100</span></div>{[['Road quality', i.roadQuality], ['Drainage coverage', i.drainageCoverage], ['Water access', i.waterAccess], ['Public transport', i.publicTransportAccess]].map(([n, v]) => <div className="bar-row" key={String(n)}><div><span>{n}</span><b>{v}%</b></div><div className="bar-track"><i style={{ width: `${v}%` }} /></div></div>)}</div> })}</div></div>;

const InvestmentSection: React.FC = () => <div className="dashboard-stack"><div className="section-intro"><div><span className="section-label">DEMAND VS INVESTMENT</span><h2>Investment coverage and mismatch signals</h2><p>Budgets below are simulated. The dashboard compares coverage against citizen demand to surface potential mismatches for human review.</p></div></div><div className="gov-card table-card"><table><thead><tr><th>Ward</th><th>Sector</th><th>Citizen demand</th><th>Allocated budget</th><th>Completion</th><th>Gap signal</th></tr></thead><tbody>{civicData.projects.slice(0, 12).map(p => { const inv = civicData.investments.find(x => x.wardId === p.wardId && x.sector === p.category) || civicData.investments.find(x => x.wardId === p.wardId && x.sector === 'Drainage')!; return <tr key={p.wardId}><td><b>{p.wardName}</b></td><td>{inv.sector}</td><td>{p.demand}/100</td><td>{money(inv.allocatedBudget)}</td><td>{inv.completionPercentage}%</td><td><span className={p.investmentGap > 60 ? 'status-high' : 'status-medium'}>{p.investmentGap}/100</span></td></tr> })}</tbody></table></div></div>;

const ProjectsSection: React.FC<{ project: PriorityProject, setSelected: (x: string) => void }> = ({ project, setSelected }) => <div className="dashboard-stack"><div className="section-intro"><div><span className="section-label">EXPLAINABLE RECOMMENDATIONS</span><h2>Priority project candidates</h2><p>These are analytical recommendations for review. No item represents an official government decision.</p></div></div><div className="project-list">{civicData.projects.map((p, i) => <div className={p.wardId === project.wardId ? 'project-card selected' : 'project-card'} key={p.wardId}><div className="project-rank">#{i + 1}</div><div className="project-main"><div className="project-title"><span>{p.category}</span><h3>{p.title}</h3><small>{p.wardName} · {p.affectedPopulation.toLocaleString()} affected population estimate</small></div><div className="factor-row">{[['Demand', p.demand], ['Severity', p.severity], ['Population', p.populationImpact], ['Infra gap', p.infrastructureGap], ['Vulnerability', p.vulnerability], ['Investment gap', p.investmentGap]].map(([n, v]) => <div key={String(n)}><span>{n}</span><b>{v}</b></div>)}</div><div className="project-evidence"><b>Why this priority?</b>{p.evidence.map(x => <span key={x}>• {x}</span>)}</div><small className="limitation">{p.limitations}</small></div><div className="project-score"><strong>{p.score}</strong><span>priority score</span><button onClick={() => setSelected(p.wardId)}>Inspect ward</button></div></div>)}</div></div>;

const RequestsSection: React.FC<{ requests: typeof civicData.requests; search: string; setSearch: (x: string) => void; category: string; setCategory: (x: string) => void }> = ({ requests, search, setSearch, category, setCategory }) => <div className="dashboard-stack"><div className="section-intro"><div><span className="section-label">CITIZEN SIGNALS</span><h2>Structured development requests</h2><p>{civicData.requests.length} dataset requests demonstrate multilingual aggregation and clustering.</p></div></div><div className="filters"><div className="search-box"><Search size={16} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search request or ward" /></div><select value={category} onChange={e => setCategory(e.target.value)}><option>All</option>{['Drainage', 'Roads', 'Water', 'Lighting', 'Waste', 'Public Transport'].map(x => <option key={x}>{x}</option>)}</select><span className="filter-count"><Filter size={15} />{requests.length} matching</span></div><div className="gov-card table-card"><table><thead><tr><th>Request</th><th>Language</th><th>Category</th><th>Severity</th><th>Ward</th><th>Impact</th></tr></thead><tbody>{requests.slice(0, 40).map(r => <tr key={r.id}><td><b>{r.id}</b><p>{r.text}</p></td><td>{langName(r.language)}</td><td>{r.category}</td><td><span className={r.severity === 'high' ? 'status-high' : r.severity === 'medium' ? 'status-medium' : 'status-low'}>{r.severity}</span></td><td>{r.ward}</td><td>{r.affectedPopulation.toLocaleString()}</td></tr>)}</tbody></table></div></div>;

const AssistantSection: React.FC<{ assistant: string; setAssistant: (x: string) => void; ask: () => void; chat: { q: string; a: string }[] }> = ({ assistant, setAssistant, ask, chat }) => <div className="assistant-page"><div className="assistant-intro"><div className="assistant-orb"><Bot /></div><span className="section-label">GOVERNMENT AI ASSISTANT</span><h2>Ask the dataset, not a generic chatbot.</h2><p>Responses are generated from CivicSignal's MongoDB-backed request, ward, infrastructure and investment data.</p><div className="suggestions">{['Which areas have the highest drainage demand?', 'Why is Ward 12 a priority?', 'Compare citizen demand with investment.', 'What are the biggest infrastructure gaps?'].map(q => <button onClick={() => setAssistant(q)} key={q}>{q}<ArrowUpRight size={14} /></button>)}</div></div><div className="assistant-chat gov-card">{chat.length === 0 && <div className="chat-empty"><Bot size={28} /><span>Start with a question about demand, gaps, investment or priority evidence.</span></div>}{chat.map((c, i) => <div className="chat-turn" key={i}><div className="chat-q">{c.q}</div><div className="chat-a"><Bot size={16} />{c.a}</div></div>)}<div className="chat-input"><input value={assistant} onChange={e => setAssistant(e.target.value)} onKeyDown={e => e.key === 'Enter' && ask()} placeholder="Ask a question about the MongoDB dataset…" /><button onClick={ask}><ArrowUpRight size={17} /></button></div></div></div>;
